import os

CSVUPLOAD_APP_SECRET_KEY = os.getenv('CSVUPLOAD_APP_SECRET_KEY')

BIDMOD_SERVER_HOST = os.getenv('BIDUNICORN_TOOL_APP_PORT_60000_TCP_ADDR')
BIDMOD_SERVER_PORT = os.getenv('BIDUNICORN_TOOL_APP_PORT_60000_TCP_PORT')

BIDMOD_FILE_DOWNLOAD_HOST = os.getenv('BIDMOD_FILE_DOWNLOAD_HOST', '148.251.133.99')
BIDMOD_FILE_DOWNLOAD_PORT = os.getenv('BIDMOD_FILE_DOWNLOAD_PORT', '60000')