import os

CSVUPLOAD_APP_SECRET_KEY = os.getenv('CSVUPLOAD_APP_SECRET_KEY')

BIDMOD_SERVER_HOST = os.getenv('BIDMOD_SERVER_HOST', '52.210.27.169')
BIDMOD_SERVER_PORT = os.getenv('BIDMOD_SERVER_PORT', '60000')