import os

CSVUPLOAD_APP_SECRET_KEY = os.getenv('CSVUPLOAD_APP_SECRET_KEY')

BIDMOD_SERVER_HOST = os.getenv('BIDMOD_SERVER_HOST', '0.0.0.0')
BIDMOD_SERVER_PORT = os.getenv('BIDMOD_SERVER_PORT', '60000')